version: '3.8'
services:
  db:
    image: postgres:15
    container_name: transfers_db_container
    environment:
      POSTGRES_DB: transfers_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"